import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import moment from 'moment'

const generatePDF = async (reportData,total,user) => {
  const doc = new jsPDF({ format: 'a4' })

  const eventsTableColumn = [
    "INDEX",
    'ROUTE NAME',
    'BUS NAME',
    'START POINT',
    'START TIME ',
    'END TIME',
    'TOTAL DISTANCE',
    'ROUTE ADDED BY',
    'ROUTE CREATED ON',
    'ROUTE TAKEN PERCENTAGE'
  ]

  const eventsTableRows = []
  reportData.forEach((data, index) => {
    const eventRowData = [
      ++index,
      data?.Routename,
      data?.bus,
      data?.startpoint,
      data?.starttime,
      data?.endtime,
      data?.totdistance+'km',
      data?.addedby,
      moment(data?.createdAt).format('YYYY-MM-DD'),
      Math.round(((data?.report.length)*100)/total)+"%",
    ]
    eventsTableRows.push(eventRowData)
  })

  doc.text(`ROUTES STATISTICS REPORT`, 70, 15)
  doc.setFontSize(10)
  doc.setTextColor('gray')
  doc.text(
    `REPORT GENERATED ON : ${moment(new Date()).format('MMMM Do YYYY, h:mm:ss a')}`,
    70.5,
    20
  )
  doc.text(
    `REPORT GENERATED BY : ${user}`,
    70.5,
    25
  )

  autoTable(doc, {
    head: [eventsTableColumn],
    body: eventsTableRows,
    headStyles: { fillColor: 'black' },
    startY: 28,
  })


  doc.save(`routes-report.pdf`)
}

export default generatePDF